#!/system/bin/sh
unset LD_PRELOAD

INTERFACE=rndis0

su -c killall arpspoof 2>/dev/null
wait 50
su -c killall arpspoof 2>/dev/null
wait 50
su -c killall urlsnarff 2>/dev/null
wait 10
su -c ifconfig $INTERFACE down

# Restoring iptables rules
su -c iptables -D FORWARD -i $INTERFACE -j ACCEPT
su -c iptables -t nat -D POSTROUTING -j MASQUERADE
su -c iptables -A natctrl_FORWARD -j DROP
# Remove iface and routes
su -c ip addr flush dev $INTERFACE
su -c ip link set $INTERFACE down


